#include <iostream>
#include <cmath>

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

using namespace std;

int getNumFactors(int num);

int p12_main(int argc, char **argv)
{
    int numFactors = 5;
    int triNum = 28;
    int num = 8;

    while(numFactors <= 500) {
        triNum += num;
        numFactors = getNumFactors(triNum);
        num++;
    }

    cout << triNum << endl;

    return 0;
}

int getNumFactors(int num)
{
    int limit = (int) sqrt(num) + 1;
    int numFactors = 0;
    for(int ii = 1; ii < limit; ii++) {
        if(num % ii == 0) {
            numFactors += 2;
        }
    }

    return numFactors;
}
